spring:

  application:
    name: checkout

  kafka:
    consumer:
      group-id: checkout-${random.uuid}
      auto-offset-reset: earliest

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

stock-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:9081,localhost:10081
    ServerListRefreshInterval: 15000